export const IMAGES = {
  bills: '/images/bills.png',
  claude_round: '/images/claude_round.png',
  commute: '/images/commute.png',
  currency: '/images/currency.png',
  currency_conversion: '/images/currency_conversion.png',
  education: '/images/education.png',
  emi: '/images/emi.png',
  entertainment: '/images/entertainment.png',
  favicon: '/images/favicon.png',
  flywire: '/images/flywire.jpg',
  food: '/images/food.png',
  gemini_round: '/images/gemini_round.png',
  healthcare: '/images/healthcare.png',
  insurance: '/images/insurance.png',
  loan_balance: '/images/loan_balance.png',
  misc: '/images/misc.png',
  poll: '/images/poll.png',
  prepayment_target: '/images/prepayment_target.png',
  rent: '/images/rent.png',
  save: '/images/save.png',
  shopping: '/images/shopping.png',
  target: '/images/target.png',
  perplexity_round: '/images/perplexity_round.png',
};

export default IMAGES;
